"""Add photo_filename column to books table

Revision ID: 55a2be9b8f29
Revises: 6689d451075e
Create Date: 2026-04-30 10:57:40.486210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a2be9b8f29'
down_revision = '6689d451075e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
