"""add role column to users

Revision ID: 6689d451075e
Revises: 08644a3b79e4
Create Date: 2026-04-29 15:24:04.587409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6689d451075e'
down_revision = '08644a3b79e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add as nullable, then set default, then make not nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
    
    # Set default role for existing users
    op.execute("UPDATE users SET role = 'borrower' WHERE role IS NULL")
    
    # Now make it not nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
